# Generated by Django 2.0 on 2019-10-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yqlj_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yqlj_name', models.CharField(max_length=50)),
                ('yqlj_urllist', models.CharField(max_length=50)),
            ],
        ),
    ]
