# Generated by Django 2.0 on 2019-10-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_information',
            name='Description',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
